server.error.whitelabel.enabled: false

spring:
  zipkin:
    base-url: http://localhost:9411/

management:
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
unik:
  service:
    message: Welcome to micrso-services demo..!!
